version: '3.7'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RedKhezuHR5
      MYSQL_PASSWORD: RedKhezuHR5
      MYSQL_USER: geoffreyturpin
      MYSQL_DATABASE: geoffreyturpin
